"""
Chat Memory — per-conversation entity tracker and reference resolver.

Stateless module: each call derives memory fresh from the message history
that the frontend sends. No backend storage needed (state lives in the
frontend's persisted zustand store).

What we track:
  - URLs visited / fetched / cited
  - Files generated (PDF, DOCX, XLSX, CSV, TXT) with format + first-line title
  - Topics / entities mentioned (light extraction)

What we do with it:
  1. extract_memory(history) → ChatMemory snapshot
  2. resolve_references(query, mem) → query with pronouns expanded inline
     ("that website" → "that website (referring to https://...)")
  3. memory_summary(mem) → formatted text block for skill prompts

The flow in /chat:
  history  →  extract  →  resolve in query  →  pass to skill context
                                              ↓
                       skill sees the resolved query AND the memory
"""
from __future__ import annotations
import re
from dataclasses import dataclass, field
from typing import Optional


# ── Data structures ────────────────────────────────────────────────────────
@dataclass
class MemoryEntity:
    kind:    str             # 'url' | 'file' | 'topic'
    label:   str             # human-readable label
    value:   str             # canonical reference (URL, fmt, topic)
    turn:    int             # which message index produced this
    context: str = ''        # surrounding snippet (160 chars)


@dataclass
class ChatMemory:
    entities: list[MemoryEntity] = field(default_factory=list)

    def latest(self, kind: str) -> Optional[MemoryEntity]:
        """Return the most-recently mentioned entity of a given kind."""
        for e in reversed(self.entities):
            if e.kind == kind:
                return e
        return None

    def latest_url(self) -> Optional[MemoryEntity]:
        return self.latest('url')

    def latest_file(self) -> Optional[MemoryEntity]:
        return self.latest('file')

    def to_dict(self) -> dict:
        return {
            "entities": [
                {"kind": e.kind, "label": e.label, "value": e.value,
                 "turn": e.turn, "context": e.context}
                for e in self.entities
            ],
            "summary": {
                "urls":  [e.value for e in self.entities if e.kind == 'url'],
                "files": [e.label for e in self.entities if e.kind == 'file'],
            },
        }


# ── Extraction patterns ────────────────────────────────────────────────────
_URL_RE = re.compile(r'https?://[^\s<>")\]]+', re.I)
_GEN_BLOCK_RE = re.compile(r'@@GENERATE:(\w+)\s*\n([\s\S]*?)@@END', re.M)
_MD_LINK_RE = re.compile(r'\[([^\]]+)\]\((https?://[^\)]+)\)')


def extract_memory(messages: list[dict]) -> ChatMemory:
    """Scan the conversation and build a ChatMemory snapshot."""
    mem = ChatMemory()
    seen_urls: set[str] = set()

    for i, msg in enumerate(messages):
        content = msg.get('content', '') or ''
        role    = msg.get('role', '')

        # URLs from anywhere in the content
        for url in _URL_RE.findall(content):
            # Strip trailing punctuation that's not part of the URL
            url = url.rstrip('.,;:!?)')
            if url not in seen_urls:
                seen_urls.add(url)
                # Try to find a markdown-link label nearby for nicer display
                label = url
                md = _MD_LINK_RE.search(content)
                if md and md.group(2) == url:
                    label = md.group(1)
                mem.entities.append(MemoryEntity(
                    kind='url', label=label, value=url, turn=i,
                    context=content[:200].strip(),
                ))

        # Files generated by the assistant
        if role == 'assistant':
            for m in _GEN_BLOCK_RE.finditer(content):
                fmt = m.group(1).lower()
                body = m.group(2).strip()
                first_line = body.split('\n', 1)[0].lstrip('#').strip()[:60]
                if not first_line:
                    first_line = f"file_{i}"
                mem.entities.append(MemoryEntity(
                    kind='file',
                    label=f"{fmt.upper()}: {first_line}" if first_line else fmt.upper(),
                    value=fmt,
                    turn=i,
                    context=body[:200],
                ))

    return mem


# ── Reference resolution ───────────────────────────────────────────────────
_REF_PATTERNS = [
    # (description, regex, entity_kind)
    ('website',  re.compile(r'\b(?:that|this|the|previous|earlier|same|their|its|on\s+(?:the|this))\s+'
                             r'(?:website|site|page|link|url|domain|homepage)s?\b', re.I), 'url'),
    ('file',     re.compile(r'\b(?:that|this|the|previous|earlier|same)\s+'
                             r'(?:file|pdf|document|spreadsheet|csv|word|excel|txt|docx|xlsx|report)s?\b', re.I), 'file'),
    ('previous', re.compile(r'\b(?:we\s+(?:discuss(?:ed)?|talk(?:ed)?\s+about|generat(?:e|ed)|'
                             r'mak(?:e|de)|creat(?:e|ed)|visit(?:ed)?|search(?:ed)?|compar(?:e|ed))|'
                             r'i\s+(?:ask(?:ed)?|generat(?:e|ed)|made|creat(?:e|ed)|visit(?:ed)?|search(?:ed)?))\b',
                             re.I), None),
]

# Implicit-continuation: queries that lack an explicit URL but clearly refer to
# subpages of "the previously discussed site". E.g.:
#   "can you find the terms of service and privacy policy and give me links"
#   "what's their phone number"
#   "do they have a careers page"
#   "find pricing"
_IMPLICIT_PAGE_RE = re.compile(
    r"\b(terms\s+of\s+service|terms\s+(?:and\s+)?conditions|privacy\s+policy|"
    r"contact\s+(?:page|info|us)|phone\s+number|email\s+address|mailing\s+address|"
    r"about\s+(?:page|us)|pricing\s+(?:page|info)|careers?\s+page|jobs?\s+page|"
    r"blog\s+post|articles?|sitemap|"
    r"their\s+(?:phone|email|address|hours|prices?|services?|products?|policies?)|"
    r"(?:find|get|show)\s+(?:me\s+)?(?:the\s+|their\s+)?(?:links?|pages?|info))\b",
    re.I,
)

_EXPLICIT_URL_IN_QUERY = re.compile(r'https?://|www\.|\b\w[\w\-]+\.(?:com|org|net|io|ai|dev|app|co)\b', re.I)


def resolve_references(query: str, mem: ChatMemory) -> str:
    """Detect pronoun/reference patterns and append concrete entities inline.

    Example:
      query: "Generate a PDF about that website"
      mem:   url=https://sher-expressllc.com
      ↓
      "Generate a PDF about that website (referring to https://sher-expressllc.com)"
    """
    additions = []
    seen = set()

    for name, pat, kind in _REF_PATTERNS:
        if pat.search(query):
            if kind == 'url':
                u = mem.latest_url()
                if u and u.value not in seen:
                    additions.append(f"the website {u.value}")
                    seen.add(u.value)
            elif kind == 'file':
                f = mem.latest_file()
                if f and f.label not in seen:
                    additions.append(f"the previously generated {f.label}")
                    seen.add(f.label)
            elif kind is None:
                # "we discussed / I asked" — add latest entities for context
                u = mem.latest_url()
                f = mem.latest_file()
                if u and u.value not in seen:
                    additions.append(f"the website {u.value}")
                    seen.add(u.value)
                if f and f.label not in seen:
                    additions.append(f"the file {f.label}")
                    seen.add(f.label)

    # Implicit follow-up: query asks about a subpage/property of the last URL
    # without naming the site. E.g. "find terms of service and privacy policy"
    # after we'd already looked at sher-expressllc.com.
    if not additions and not _EXPLICIT_URL_IN_QUERY.search(query) and _IMPLICIT_PAGE_RE.search(query):
        u = mem.latest_url()
        if u:
            additions.append(f"on the website {u.value}")

    if not additions:
        return query
    return f"{query}\n\n[Context — earlier in this chat: {'; '.join(additions)}]"


# ── Memory summary for skill prompts ───────────────────────────────────────
def memory_summary(mem: ChatMemory, max_items: int = 8) -> str:
    """Format memory entities as a context block for LLM prompts."""
    if not mem.entities:
        return ''

    recent = mem.entities[-max_items:]
    by_kind: dict[str, list[MemoryEntity]] = {}
    for e in recent:
        by_kind.setdefault(e.kind, []).append(e)

    lines = ['Earlier in this conversation:']
    if 'url' in by_kind:
        lines.append('  Web pages discussed:')
        for e in by_kind['url']:
            lines.append(f'    - {e.value}')
    if 'file' in by_kind:
        lines.append('  Files generated:')
        for e in by_kind['file']:
            lines.append(f'    - {e.label}')
    return '\n'.join(lines)
